### ISSUE TITLE
Upgrade TOR to 0.2.8.9

### ISSUE THREAD

**Issue by blackfuel** [RMerl/asuswrt-merlin#1067]
It compiles and runs fine on 380.63-alpha2 without any changes.
My primary usage is as a TOR transparent proxy for the LAN with Dnsmasq resolving the .onion domains too.

**Comment by feranick** [comment]
Changelog (security fix): https://blog.torproject.org/blog/tor-0289-released-important-fixes

- Major features (security fixes):
Prevent a class of security bugs caused by treating the contents of a buffer chunk as if they were a NUL-terminated string. At least one such bug seems to be present in all currently used versions of Tor, and would allow an attacker to remotely crash most Tor instances, especially those compiled with extra compiler hardening. With this defense in place, such bugs can't crash Tor, though we should still fix them as they occur. Closes ticket 20384 (TROVE-2016-10-001).
- Minor features (geoip):
Update geoip and geoip6 to the October 4 2016 Maxmind GeoLite2 Country database.
