### ISSUE TITLE
380.62_1 Passwords are stored in cleartext

### ISSUE THREAD

**Issue by Zulgrib** [RMerl/asuswrt-merlin#1070]
In 380.62_1

Storing passwords in cleartext is not good practice, they should be hashed.

Passwords appears in cleartext in both acc_list and http_passwd

**Comment by RMerl** [comment]
Changing this would break backward compatibility, and introduce issues such as locking you out of your router if changing back to Asus's stock firmware or an older firmware.  Therefore it's not something I can easily change, it will have to be done upstream by Asus.

**Comment by Zulgrib** [comment]
Can't the switching back to ASUS firmware be resolved by reset in this case ?

**Comment by RMerl** [comment]
Switching back to either Asus's stock firmware or an older version of my firmware will require doing a factory default reset, wiping out all your configuration.  That's something I want to avoid, since one of the advantages of this firmware is the ease of moving back and forth between versions, compared to a pure third party such as DD-WRT or Tomato which makes a factory default reset mandatory.

**Comment by Zulgrib** [comment]
Okay, contacted the people in charge of the routers at ASUS France, but they are not a security team, if you have a better contact entry for that matters I would gladly contact them.
