### ISSUE TITLE
Wrong log levels DDNS (Remote Log Server)

### ISSUE THREAD

**Issue by DcR-NL** [RMerl/asuswrt-merlin#1247]
(380.65 - N66U)
Using Namecheap DDNS and remote logging with the following settings:

1. Default loglevel: Error
2. Log only messages more urgent than: Error.

Syslog reports DDNS messages with a far too high log level. Example output on a forced update:
```
(EMERGENCY) Feb 18 17:36:31 ddns update: ez-ipupdate: starting...
(EMERGENCY) Feb 18 17:36:31 ddns update: connected to dynamicdns.park-your-domain.com (104.219.249.25) on port 80.
(EMERGENCY) Feb 18 17:36:32 ddns update: request successful
(EMERGENCY) Feb 18 17:36:32 ddns update: asusddns_update: 0
```
As the request appears to be successful, I would expect these to be of the notice-level or lower. Or am I missing something?

**Comment by RMerl** [comment]
Logging done by the router firmware itself (and not by services) is all done at the same level.  This is because the firmware logging functions weren't designed to handle multiple levels.  Changing this would require hundreds of changes all over the firmware, so won't be happening.

You can change the global level used by the firmware under Administration -> System.
