### ISSUE TITLE
AC68U - 380.65 stops tesponding on wan port

### ISSUE THREAD

**Issue by larsosca** [RMerl/asuswrt-merlin#1257]
I have installed 380.65 and after a while the router stops responding to ping and port forwarding on the wan port.
Sometimes i lose the internet connection from LAN as well.
Restarting the router works for only some minutes.

I have tested this on two separate RT-AC68U with the same result.
I have also performed a factory reset and reconfigured, still the same problem.

**Comment by petertfm** [comment]
I too had similar issues on my rt-ac88u, IP4 would go down every day once or twice for around 10 minutes but I didn't notice sometimes because google services use IP6. I reinstalled 64 and no more ip4 problems

Not sure if its the cause but my ISP only leases addresses for 4 hours.

Hoping 66 wont have same issue

**Comment by RMerl** [comment]
Please use the support forums at SNBForums for support requests.
