### ISSUE TITLE
Change behavior of WPS button to toggle radio wifi in ASUS RT-AC66U B1

### ISSUE THREAD

**Issue by srgcdev** [RMerl/asuswrt-merlin#1272]
Hello,

The firmware of ASUS RT-AC66U B1 router is the same that ASUS RT-AC68U.

ASUS RT-AC68U has a physical button to toggle the radio wifi but ASUS RT-AC66U B1 hasn't.

So it would be necessary to add an option to change the behavior of WPS button to toggle radio wifi for ASUS RT-AC66U B1.

Thanks.

**Comment by RMerl** [comment]
Duplicate #1021

**Comment by srgcdev** [comment]
@RMerl, #1021 describes a problem with LED's. The problem I describe here is related to have a physical button to toggle radio wifi changing the behavior of WPS button. So i think is not duplicated.
Thanks.

**Comment by RMerl** [comment]
I posted in that other issue that I had no intention of hardcoding a specific feature, because there's always someone else asking for yet another feature.  Instead, the plan outlined in that other issue is to make it run any user script written by the user, which would allow the button to be used for any functionality desired by the user.  However that's a low priority, and I haven't found the time to implement this yet, so there's no ETA.
