### ISSUE TITLE
Firmware: 380.66_4 / Router: RT-AC66U - OpenVPN Client GUI Settings Bug

### ISSUE THREAD

**Issue by singhandsingh** [RMerl/asuswrt-merlin#1379]
I upgraded to 380.66_4, did a firmware reset and reconfigured my router manually with the same settings. 

Everything was perfect with the exception of the OpenVPN client configuration to StrongVPN. The client connected just fine, however traffic was not flowing through the tunnel (even though I had redirected all traffic). I tested the same configuration on my Windows OpenVPN client with no problems..

After some tweaking around, I realised that the "Compression -> None" option in the GUI was not enforced. I finally started seeing traffic through the tunnel after I inserted the customer config..

> comp-lzo no

Is this a bug in the GUI implementation ?

p/s: I have a separate issue pertaining to the DNS not resolving when all traffic is routed through the tunnel. I will post a separate bug report for that...

**Comment by RMerl** [comment]
OpenVPN 2.4 changed the way compression is configured, due to the addition of lz4 support.  comp-lzo is now deprecated, and the new equivalence to "comp-lzo no" is "compress" without any parameter according to the OpenVPN 2.4 [manual](https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage).

Note that "None" does not disable compression - it will merely not enable it, still allowing the remote server to enable it through a pushed option.  You have to use "Disabled" if you want to completely disable compression support.
