### ISSUE TITLE
Update curl to 7.55.0

### ISSUE THREAD

**Issue by CorrosiveCat** [RMerl/asuswrt-merlin#1450]
Seems to add a few features and bug fixes and might be helpful

**Comment by RMerl** [comment]
I tried upgrading to 7.55.1, and it causes a kernel panic at boot time.  Could be some internal changes that aren't compatible with rc (which is linked against it).  If the issue lies in the closed source components of rc, then it means it won't be possible to upgrade to any future curl release.  At this time I have no idea as to the cause - debugging the init process is quite difficult since any crash in it will cause an early reboot.

**Comment by RMerl** [comment]
libcurl is linked against rc/dsl_fb.o, which is closed source.  That means only Asus would be able to fix this issue.
