### ISSUE TITLE
Time Scheduling and Email

### ISSUE THREAD

**Issue by davidbradtberg** [RMerl/asuswrt-merlin#937]
I currently have been using a Fritz Box for a number of years and just bought the ASUS RT-AC88u and the only things I am missing is a finer granularity in the Time Scheduling I used to block just 30 minutes for meal times to force the kids off.

I also used to get nice daily email reports of online time.

Is it possible to break the current 1 hours blocks further or have I missed something that is already available.

Also the ability to get email alerts would be very useful and support for more than the limited email systems.

**Comment by RMerl** [comment]
That would be tricky to implement due to the way Asus designed the UI.  I've forwarded that request to them last year, it will be up to them to decide if they want to implement it - not something I can do with the existing UI code.

Email notification is something they seem to still be working on, so I don't want to touch it, and leave it to them as well.
